/* File: hw2mod2module.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Mon Nov 13 19:25:24 2017
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *hw2mod2_error;
static PyObject *hw2mod2_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#define PRINTPYOBJERR(obj)\
  fprintf(stderr,"hw2mod2.error is related to ");\
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");

#define pyobj_from_double1(v) (PyFloat_FromDouble(v))
#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (((PyArrayObject *)(capi_ ## var ## _tmp))->nd)
#define old_shape(var,dim) (((PyArrayObject *)(capi_ ## var ## _tmp))->dimensions[dim])
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

/* New SciPy */
#define TRYPYARRAYTEMPLATECHAR case NPY_STRING: *(char *)(arr->data)=*v; break;
#define TRYPYARRAYTEMPLATELONG case NPY_LONG: *(long *)(arr->data)=*v; break;
#define TRYPYARRAYTEMPLATEOBJECT case NPY_OBJECT: (arr->descr->f->setitem)(pyobj_from_ ## ctype ## 1(*v),arr->data); break;

#define TRYPYARRAYTEMPLATE(ctype,typecode) \
        PyArrayObject *arr = NULL;\
        if (!obj) return -2;\
        if (!PyArray_Check(obj)) return -1;\
        if (!(arr=(PyArrayObject *)obj)) {fprintf(stderr,"TRYPYARRAYTEMPLATE:");PRINTPYOBJERR(obj);return 0;}\
        if (arr->descr->type==typecode)  {*(ctype *)(arr->data)=*v; return 1;}\
        switch (arr->descr->type_num) {\
                case NPY_DOUBLE: *(double *)(arr->data)=*v; break;\
                case NPY_INT: *(int *)(arr->data)=*v; break;\
                case NPY_LONG: *(long *)(arr->data)=*v; break;\
                case NPY_FLOAT: *(float *)(arr->data)=*v; break;\
                case NPY_CDOUBLE: *(double *)(arr->data)=*v; break;\
                case NPY_CFLOAT: *(float *)(arr->data)=*v; break;\
                case NPY_BOOL: *(npy_bool *)(arr->data)=(*v!=0); break;\
                case NPY_UBYTE: *(unsigned char *)(arr->data)=*v; break;\
                case NPY_BYTE: *(signed char *)(arr->data)=*v; break;\
                case NPY_SHORT: *(short *)(arr->data)=*v; break;\
                case NPY_USHORT: *(npy_ushort *)(arr->data)=*v; break;\
                case NPY_UINT: *(npy_uint *)(arr->data)=*v; break;\
                case NPY_ULONG: *(npy_ulong *)(arr->data)=*v; break;\
                case NPY_LONGLONG: *(npy_longlong *)(arr->data)=*v; break;\
                case NPY_ULONGLONG: *(npy_ulonglong *)(arr->data)=*v; break;\
                case NPY_LONGDOUBLE: *(npy_longdouble *)(arr->data)=*v; break;\
                case NPY_CLONGDOUBLE: *(npy_longdouble *)(arr->data)=*v; break;\
                case NPY_OBJECT: (arr->descr->f->setitem)(pyobj_from_ ## ctype ## 1(*v),arr->data, arr); break;\
        default: return -2;\
        };\
        return 1


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int try_pyarr_from_double(PyObject* obj,double* v) {
  TRYPYARRAYTEMPLATE(double,'d');
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = hw2mod2_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/*********************************** costj ***********************************/
static char doc_f2py_rout_hw2mod2_cost_costj[] = "\
j = costj(x)\n\nWrapper for ``costj``.\
\n\nParameters\n----------\n"
"x : input rank-1 array('d') with bounds (f2py_x_d0)\n"
"\nReturns\n-------\n"
"j : float";
/* #declfortranroutine# */
static PyObject *f2py_rout_hw2mod2_cost_costj(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *x = NULL;
  npy_intp x_Dims[1] = {-1};
  const int x_Rank = 1;
  PyArrayObject *capi_x_tmp = NULL;
  int capi_x_intent = 0;
  PyObject *x_capi = Py_None;
  double j = 0;
  int f2py_x_d0 = 0;
  static char *capi_kwlist[] = {"x",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:hw2mod2.cost.costj",\
    capi_kwlist,&x_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable x */
  ;
  capi_x_intent |= F2PY_INTENT_IN;
  capi_x_tmp = array_from_pyobj(NPY_DOUBLE,x_Dims,x_Rank,capi_x_intent,x_capi);
  if (capi_x_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(hw2mod2_error,"failed in converting 1st argument `x' of hw2mod2.cost.costj to C/Fortran array" );
  } else {
    x = (double *)(capi_x_tmp->data);

  /* Processing variable j */
  /* Processing variable f2py_x_d0 */
  f2py_x_d0 = shape(x, 0);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(x,&j,&f2py_x_d0);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",j);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable f2py_x_d0 */
  /* End of cleaning variable j */
  if((PyObject *)capi_x_tmp!=x_capi) {
    Py_XDECREF(capi_x_tmp); }
  }  /*if (capi_x_tmp == NULL) ... else of x*/
  /* End of cleaning variable x */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of costj ********************************/

/******************************** costj_grad2d ********************************/
static char doc_f2py_rout_hw2mod2_cost_costj_grad2d[] = "\
j_grad = costj_grad2d(x)\n\nWrapper for ``costj_grad2d``.\
\n\nParameters\n----------\n"
"x : input rank-1 array('d') with bounds (f2py_x_d0)\n"
"\nReturns\n-------\n"
"j_grad : rank-1 array('d') with bounds (size(x))";
/* #declfortranroutine# */
static PyObject *f2py_rout_hw2mod2_cost_costj_grad2d(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *x = NULL;
  npy_intp x_Dims[1] = {-1};
  const int x_Rank = 1;
  PyArrayObject *capi_x_tmp = NULL;
  int capi_x_intent = 0;
  PyObject *x_capi = Py_None;
  double *j_grad = NULL;
  npy_intp j_grad_Dims[1] = {-1};
  const int j_grad_Rank = 1;
  PyArrayObject *capi_j_grad_tmp = NULL;
  int capi_j_grad_intent = 0;
  int f2py_x_d0 = 0;
  static char *capi_kwlist[] = {"x",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:hw2mod2.cost.costj_grad2d",\
    capi_kwlist,&x_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable x */
  ;
  capi_x_intent |= F2PY_INTENT_IN;
  capi_x_tmp = array_from_pyobj(NPY_DOUBLE,x_Dims,x_Rank,capi_x_intent,x_capi);
  if (capi_x_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(hw2mod2_error,"failed in converting 1st argument `x' of hw2mod2.cost.costj_grad2d to C/Fortran array" );
  } else {
    x = (double *)(capi_x_tmp->data);

  /* Processing variable j_grad */
  j_grad_Dims[0]=size(x);
  capi_j_grad_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_j_grad_tmp = array_from_pyobj(NPY_DOUBLE,j_grad_Dims,j_grad_Rank,capi_j_grad_intent,Py_None);
  if (capi_j_grad_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(hw2mod2_error,"failed in converting hidden `j_grad' of hw2mod2.cost.costj_grad2d to C/Fortran array" );
  } else {
    j_grad = (double *)(capi_j_grad_tmp->data);

  /* Processing variable f2py_x_d0 */
  f2py_x_d0 = shape(x, 0);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(x,j_grad,&f2py_x_d0);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_j_grad_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable f2py_x_d0 */
  }  /*if (capi_j_grad_tmp == NULL) ... else of j_grad*/
  /* End of cleaning variable j_grad */
  if((PyObject *)capi_x_tmp!=x_capi) {
    Py_XDECREF(capi_x_tmp); }
  }  /*if (capi_x_tmp == NULL) ... else of x*/
  /* End of cleaning variable x */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of costj_grad2d ****************************/

/******************************** costj_hess2d ********************************/
static char doc_f2py_rout_hw2mod2_cost_costj_hess2d[] = "\
j_hess = costj_hess2d(x)\n\nWrapper for ``costj_hess2d``.\
\n\nParameters\n----------\n"
"x : input rank-1 array('d') with bounds (f2py_x_d0)\n"
"\nReturns\n-------\n"
"j_hess : rank-2 array('d') with bounds (size(x),size(x))";
/* #declfortranroutine# */
static PyObject *f2py_rout_hw2mod2_cost_costj_hess2d(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *x = NULL;
  npy_intp x_Dims[1] = {-1};
  const int x_Rank = 1;
  PyArrayObject *capi_x_tmp = NULL;
  int capi_x_intent = 0;
  PyObject *x_capi = Py_None;
  double *j_hess = NULL;
  npy_intp j_hess_Dims[2] = {-1, -1};
  const int j_hess_Rank = 2;
  PyArrayObject *capi_j_hess_tmp = NULL;
  int capi_j_hess_intent = 0;
  int f2py_x_d0 = 0;
  static char *capi_kwlist[] = {"x",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:hw2mod2.cost.costj_hess2d",\
    capi_kwlist,&x_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable x */
  ;
  capi_x_intent |= F2PY_INTENT_IN;
  capi_x_tmp = array_from_pyobj(NPY_DOUBLE,x_Dims,x_Rank,capi_x_intent,x_capi);
  if (capi_x_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(hw2mod2_error,"failed in converting 1st argument `x' of hw2mod2.cost.costj_hess2d to C/Fortran array" );
  } else {
    x = (double *)(capi_x_tmp->data);

  /* Processing variable j_hess */
  j_hess_Dims[0]=size(x),j_hess_Dims[1]=size(x);
  capi_j_hess_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_j_hess_tmp = array_from_pyobj(NPY_DOUBLE,j_hess_Dims,j_hess_Rank,capi_j_hess_intent,Py_None);
  if (capi_j_hess_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(hw2mod2_error,"failed in converting hidden `j_hess' of hw2mod2.cost.costj_hess2d to C/Fortran array" );
  } else {
    j_hess = (double *)(capi_j_hess_tmp->data);

  /* Processing variable f2py_x_d0 */
  f2py_x_d0 = shape(x, 0);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(x,j_hess,&f2py_x_d0);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_j_hess_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable f2py_x_d0 */
  }  /*if (capi_j_hess_tmp == NULL) ... else of j_hess*/
  /* End of cleaning variable j_hess */
  if((PyObject *)capi_x_tmp!=x_capi) {
    Py_XDECREF(capi_x_tmp); }
  }  /*if (capi_x_tmp == NULL) ... else of x*/
  /* End of cleaning variable x */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of costj_hess2d ****************************/

/********************************* add_noise *********************************/
static char doc_f2py_rout_hw2mod2_cost_add_noise[] = "\
add_noise(x,j)\n\nWrapper for ``add_noise``.\
\n\nParameters\n----------\n"
"x : input rank-1 array('d') with bounds (f2py_x_d0)\n"
"j : in/output rank-0 array(float,'d')";
/* #declfortranroutine# */
static PyObject *f2py_rout_hw2mod2_cost_add_noise(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *x = NULL;
  npy_intp x_Dims[1] = {-1};
  const int x_Rank = 1;
  PyArrayObject *capi_x_tmp = NULL;
  int capi_x_intent = 0;
  PyObject *x_capi = Py_None;
  double j = 0;
  PyObject *j_capi = Py_None;
  int f2py_x_d0 = 0;
  static char *capi_kwlist[] = {"x","j",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO:hw2mod2.cost.add_noise",\
    capi_kwlist,&x_capi,&j_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable x */
  ;
  capi_x_intent |= F2PY_INTENT_IN;
  capi_x_tmp = array_from_pyobj(NPY_DOUBLE,x_Dims,x_Rank,capi_x_intent,x_capi);
  if (capi_x_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(hw2mod2_error,"failed in converting 1st argument `x' of hw2mod2.cost.add_noise to C/Fortran array" );
  } else {
    x = (double *)(capi_x_tmp->data);

  /* Processing variable j */
    f2py_success = double_from_pyobj(&j,j_capi,"hw2mod2.cost.add_noise() 2nd argument (j) can't be converted to double");
  if (f2py_success) {
  /* Processing variable f2py_x_d0 */
  f2py_x_d0 = shape(x, 0);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(x,&j,&f2py_x_d0);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
  f2py_success = try_pyarr_from_double(j_capi,&j);
  if (f2py_success) {
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
  } /*if (f2py_success) of j pyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable f2py_x_d0 */
  } /*if (f2py_success) of j*/
  /* End of cleaning variable j */
  if((PyObject *)capi_x_tmp!=x_capi) {
    Py_XDECREF(capi_x_tmp); }
  }  /*if (capi_x_tmp == NULL) ... else of x*/
  /* End of cleaning variable x */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of add_noise ******************************/

/*********************************** newton ***********************************/
static char doc_f2py_rout_hw2mod2_hw2_newton[] = "\
xf,jf,i2 = newton(xguess)\n\nWrapper for ``newton``.\
\n\nParameters\n----------\n"
"xguess : input rank-2 array('d') with bounds (f2py_xguess_d0,f2py_xguess_d1)\n"
"\nReturns\n-------\n"
"xf : rank-2 array('d') with bounds (size(xguess),1)\n"
"jf : float\n"
"i2 : int";
/* #declfortranroutine# */
static PyObject *f2py_rout_hw2mod2_hw2_newton(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *xguess = NULL;
  npy_intp xguess_Dims[2] = {-1, -1};
  const int xguess_Rank = 2;
  PyArrayObject *capi_xguess_tmp = NULL;
  int capi_xguess_intent = 0;
  PyObject *xguess_capi = Py_None;
  double *xf = NULL;
  npy_intp xf_Dims[2] = {-1, -1};
  const int xf_Rank = 2;
  PyArrayObject *capi_xf_tmp = NULL;
  int capi_xf_intent = 0;
  double jf = 0;
  int i2 = 0;
  int f2py_xguess_d0 = 0;
  int f2py_xguess_d1 = 0;
  static char *capi_kwlist[] = {"xguess",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:hw2mod2.hw2.newton",\
    capi_kwlist,&xguess_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable i2 */
  /* Processing variable jf */
  /* Processing variable xguess */
  ;
  capi_xguess_intent |= F2PY_INTENT_IN;
  capi_xguess_tmp = array_from_pyobj(NPY_DOUBLE,xguess_Dims,xguess_Rank,capi_xguess_intent,xguess_capi);
  if (capi_xguess_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(hw2mod2_error,"failed in converting 1st argument `xguess' of hw2mod2.hw2.newton to C/Fortran array" );
  } else {
    xguess = (double *)(capi_xguess_tmp->data);

  /* Processing variable xf */
  xf_Dims[0]=size(xguess),xf_Dims[1]=1;
  capi_xf_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_xf_tmp = array_from_pyobj(NPY_DOUBLE,xf_Dims,xf_Rank,capi_xf_intent,Py_None);
  if (capi_xf_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(hw2mod2_error,"failed in converting hidden `xf' of hw2mod2.hw2.newton to C/Fortran array" );
  } else {
    xf = (double *)(capi_xf_tmp->data);

  /* Processing variable f2py_xguess_d0 */
  f2py_xguess_d0 = shape(xguess, 0);
  /* Processing variable f2py_xguess_d1 */
  f2py_xguess_d1 = shape(xguess, 1);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(xguess,xf,&jf,&i2,&f2py_xguess_d0,&f2py_xguess_d1);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("Ndi",capi_xf_tmp,jf,i2);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable f2py_xguess_d1 */
  /* End of cleaning variable f2py_xguess_d0 */
  }  /*if (capi_xf_tmp == NULL) ... else of xf*/
  /* End of cleaning variable xf */
  if((PyObject *)capi_xguess_tmp!=xguess_capi) {
    Py_XDECREF(capi_xguess_tmp); }
  }  /*if (capi_xguess_tmp == NULL) ... else of xguess*/
  /* End of cleaning variable xguess */
  /* End of cleaning variable jf */
  /* End of cleaning variable i2 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of newton *******************************/

/****************************** bracket_descent ******************************/
static char doc_f2py_rout_hw2mod2_hw2_bracket_descent[] = "\
xf,jf,i2 = bracket_descent(xguess)\n\nWrapper for ``bracket_descent``.\
\n\nParameters\n----------\n"
"xguess : input rank-1 array('d') with bounds (2)\n"
"\nReturns\n-------\n"
"xf : rank-1 array('d') with bounds (2)\n"
"jf : float\n"
"i2 : int";
/*  */
static PyObject *f2py_rout_hw2mod2_hw2_bracket_descent(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *xguess = NULL;
  npy_intp xguess_Dims[1] = {-1};
  const int xguess_Rank = 1;
  PyArrayObject *capi_xguess_tmp = NULL;
  int capi_xguess_intent = 0;
  PyObject *xguess_capi = Py_None;
  double *xf = NULL;
  npy_intp xf_Dims[1] = {-1};
  const int xf_Rank = 1;
  PyArrayObject *capi_xf_tmp = NULL;
  int capi_xf_intent = 0;
  double jf = 0;
  int i2 = 0;
  static char *capi_kwlist[] = {"xguess",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:hw2mod2.hw2.bracket_descent",\
    capi_kwlist,&xguess_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable i2 */
  /* Processing variable xf */
  xf_Dims[0]=2;
  capi_xf_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_xf_tmp = array_from_pyobj(NPY_DOUBLE,xf_Dims,xf_Rank,capi_xf_intent,Py_None);
  if (capi_xf_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(hw2mod2_error,"failed in converting hidden `xf' of hw2mod2.hw2.bracket_descent to C/Fortran array" );
  } else {
    xf = (double *)(capi_xf_tmp->data);

  /* Processing variable jf */
  /* Processing variable xguess */
  xguess_Dims[0]=2;
  capi_xguess_intent |= F2PY_INTENT_IN;
  capi_xguess_tmp = array_from_pyobj(NPY_DOUBLE,xguess_Dims,xguess_Rank,capi_xguess_intent,xguess_capi);
  if (capi_xguess_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(hw2mod2_error,"failed in converting 1st argument `xguess' of hw2mod2.hw2.bracket_descent to C/Fortran array" );
  } else {
    xguess = (double *)(capi_xguess_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(xguess,xf,&jf,&i2);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("Ndi",capi_xf_tmp,jf,i2);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_xguess_tmp!=xguess_capi) {
    Py_XDECREF(capi_xguess_tmp); }
  }  /*if (capi_xguess_tmp == NULL) ... else of xguess*/
  /* End of cleaning variable xguess */
  /* End of cleaning variable jf */
  }  /*if (capi_xf_tmp == NULL) ... else of xf*/
  /* End of cleaning variable xf */
  /* End of cleaning variable i2 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/*************************** end of bracket_descent ***************************/

/******************************* bd_initialize *******************************/
static char doc_f2py_rout_hw2mod2_hw2_bd_initialize[] = "\
x3,j3 = bd_initialize(xguess)\n\nWrapper for ``bd_initialize``.\
\n\nParameters\n----------\n"
"xguess : input rank-1 array('d') with bounds (2)\n"
"\nReturns\n-------\n"
"x3 : rank-2 array('d') with bounds (3,2)\n"
"j3 : rank-1 array('d') with bounds (3)";
/*  */
static PyObject *f2py_rout_hw2mod2_hw2_bd_initialize(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *xguess = NULL;
  npy_intp xguess_Dims[1] = {-1};
  const int xguess_Rank = 1;
  PyArrayObject *capi_xguess_tmp = NULL;
  int capi_xguess_intent = 0;
  PyObject *xguess_capi = Py_None;
  double *x3 = NULL;
  npy_intp x3_Dims[2] = {-1, -1};
  const int x3_Rank = 2;
  PyArrayObject *capi_x3_tmp = NULL;
  int capi_x3_intent = 0;
  double *j3 = NULL;
  npy_intp j3_Dims[1] = {-1};
  const int j3_Rank = 1;
  PyArrayObject *capi_j3_tmp = NULL;
  int capi_j3_intent = 0;
  static char *capi_kwlist[] = {"xguess",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:hw2mod2.hw2.bd_initialize",\
    capi_kwlist,&xguess_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable xguess */
  xguess_Dims[0]=2;
  capi_xguess_intent |= F2PY_INTENT_IN;
  capi_xguess_tmp = array_from_pyobj(NPY_DOUBLE,xguess_Dims,xguess_Rank,capi_xguess_intent,xguess_capi);
  if (capi_xguess_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(hw2mod2_error,"failed in converting 1st argument `xguess' of hw2mod2.hw2.bd_initialize to C/Fortran array" );
  } else {
    xguess = (double *)(capi_xguess_tmp->data);

  /* Processing variable j3 */
  j3_Dims[0]=3;
  capi_j3_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_j3_tmp = array_from_pyobj(NPY_DOUBLE,j3_Dims,j3_Rank,capi_j3_intent,Py_None);
  if (capi_j3_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(hw2mod2_error,"failed in converting hidden `j3' of hw2mod2.hw2.bd_initialize to C/Fortran array" );
  } else {
    j3 = (double *)(capi_j3_tmp->data);

  /* Processing variable x3 */
  x3_Dims[0]=3,x3_Dims[1]=2;
  capi_x3_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_x3_tmp = array_from_pyobj(NPY_DOUBLE,x3_Dims,x3_Rank,capi_x3_intent,Py_None);
  if (capi_x3_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(hw2mod2_error,"failed in converting hidden `x3' of hw2mod2.hw2.bd_initialize to C/Fortran array" );
  } else {
    x3 = (double *)(capi_x3_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(xguess,x3,j3);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NN",capi_x3_tmp,capi_j3_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_x3_tmp == NULL) ... else of x3*/
  /* End of cleaning variable x3 */
  }  /*if (capi_j3_tmp == NULL) ... else of j3*/
  /* End of cleaning variable j3 */
  if((PyObject *)capi_xguess_tmp!=xguess_capi) {
    Py_XDECREF(capi_xguess_tmp); }
  }  /*if (capi_xguess_tmp == NULL) ... else of xguess*/
  /* End of cleaning variable xguess */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of bd_initialize ****************************/

/***************************** convergence_check *****************************/
static char doc_f2py_rout_hw2mod2_hw2_convergence_check[] = "\
flag_converged = convergence_check(j1,j2)\n\nWrapper for ``convergence_check``.\
\n\nParameters\n----------\n"
"j1 : input float\n"
"j2 : input float\n"
"\nReturns\n-------\n"
"flag_converged : int";
/*  */
static PyObject *f2py_rout_hw2mod2_hw2_convergence_check(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double j1 = 0;
  PyObject *j1_capi = Py_None;
  double j2 = 0;
  PyObject *j2_capi = Py_None;
  int flag_converged = 0;
  static char *capi_kwlist[] = {"j1","j2",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO:hw2mod2.hw2.convergence_check",\
    capi_kwlist,&j1_capi,&j2_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable flag_converged */
  /* Processing variable j1 */
    f2py_success = double_from_pyobj(&j1,j1_capi,"hw2mod2.hw2.convergence_check() 1st argument (j1) can't be converted to double");
  if (f2py_success) {
  /* Processing variable j2 */
    f2py_success = double_from_pyobj(&j2,j2_capi,"hw2mod2.hw2.convergence_check() 2nd argument (j2) can't be converted to double");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&j1,&j2,&flag_converged);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",flag_converged);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of j2*/
  /* End of cleaning variable j2 */
  } /*if (f2py_success) of j1*/
  /* End of cleaning variable j1 */
  /* End of cleaning variable flag_converged */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************** end of convergence_check **************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/

static FortranDataDef f2py_cost_def[] = {
  {"c_noise",0,{{-1}},NPY_INT},
  {"c_noise_amp",0,{{-1}},NPY_DOUBLE},
  {"costj",-1,{{-1}},0,NULL,(void *)f2py_rout_hw2mod2_cost_costj,doc_f2py_rout_hw2mod2_cost_costj},
  {"costj_grad2d",-1,{{-1}},0,NULL,(void *)f2py_rout_hw2mod2_cost_costj_grad2d,doc_f2py_rout_hw2mod2_cost_costj_grad2d},
  {"costj_hess2d",-1,{{-1}},0,NULL,(void *)f2py_rout_hw2mod2_cost_costj_hess2d,doc_f2py_rout_hw2mod2_cost_costj_hess2d},
  {"add_noise",-1,{{-1}},0,NULL,(void *)f2py_rout_hw2mod2_cost_add_noise,doc_f2py_rout_hw2mod2_cost_add_noise},
  {NULL}
};

static void f2py_setup_cost(char *c_noise,char *c_noise_amp,char *costj,char *costj_grad2d,char *costj_hess2d,char *add_noise) {
  int i_f2py=0;
  f2py_cost_def[i_f2py++].data = c_noise;
  f2py_cost_def[i_f2py++].data = c_noise_amp;
  f2py_cost_def[i_f2py++].data = costj;
  f2py_cost_def[i_f2py++].data = costj_grad2d;
  f2py_cost_def[i_f2py++].data = costj_hess2d;
  f2py_cost_def[i_f2py++].data = add_noise;
}
extern void F_FUNC(f2pyinitcost,F2PYINITCOST)(void (*)(char*,char*,char *,char *,char *,char *));
static void f2py_init_cost(void) {
  F_FUNC(f2pyinitcost,F2PYINITCOST)(f2py_setup_cost);
}


static FortranDataDef f2py_hw2_def[] = {
  {"xpath",2,{{-1,-1}},NPY_DOUBLE},
  {"jpath",1,{{-1}},NPY_DOUBLE},
  {"tol",0,{{-1}},NPY_DOUBLE},
  {"itermax",0,{{-1}},NPY_INT},
  {"newton",-1,{{-1}},0,NULL,(void *)f2py_rout_hw2mod2_hw2_newton,doc_f2py_rout_hw2mod2_hw2_newton},
  {"bracket_descent",-1,{{-1}},0,NULL,(void *)f2py_rout_hw2mod2_hw2_bracket_descent,doc_f2py_rout_hw2mod2_hw2_bracket_descent},
  {"bd_initialize",-1,{{-1}},0,NULL,(void *)f2py_rout_hw2mod2_hw2_bd_initialize,doc_f2py_rout_hw2mod2_hw2_bd_initialize},
  {"convergence_check",-1,{{-1}},0,NULL,(void *)f2py_rout_hw2mod2_hw2_convergence_check,doc_f2py_rout_hw2mod2_hw2_convergence_check},
  {NULL}
};

static void f2py_setup_hw2(void (*xpath)(int*,int*,void(*)(char*,int*),int*),void (*jpath)(int*,int*,void(*)(char*,int*),int*),char *tol,char *itermax,char *newton,char *bracket_descent,char *bd_initialize,char *convergence_check) {
  int i_f2py=0;
  f2py_hw2_def[i_f2py++].func = xpath;
  f2py_hw2_def[i_f2py++].func = jpath;
  f2py_hw2_def[i_f2py++].data = tol;
  f2py_hw2_def[i_f2py++].data = itermax;
  f2py_hw2_def[i_f2py++].data = newton;
  f2py_hw2_def[i_f2py++].data = bracket_descent;
  f2py_hw2_def[i_f2py++].data = bd_initialize;
  f2py_hw2_def[i_f2py++].data = convergence_check;
}
extern void F_FUNC(f2pyinithw2,F2PYINITHW2)(void (*)(void (*)(int*,int*,void(*)(char*,int*),int*),void (*)(int*,int*,void(*)(char*,int*),int*),char*,char*,char *,char *,char *,char *));
static void f2py_init_hw2(void) {
  F_FUNC(f2pyinithw2,F2PYINITHW2)(f2py_setup_hw2);
}

/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "hw2mod2",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_hw2mod2(void) {
#else
#define RETVAL
PyMODINIT_FUNC inithw2mod2(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = hw2mod2_module = PyModule_Create(&moduledef);
#else
  m = hw2mod2_module = Py_InitModule("hw2mod2", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module hw2mod2 (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'hw2mod2' is auto-generated with f2py (version:2).\nFunctions:\n"
"Fortran 90/95 modules:\n""  cost --- c_noise,c_noise_amp,costj(),costj_grad2d(),costj_hess2d(),add_noise()""  hw2 --- xpath,jpath,tol,itermax,newton(),bracket_descent(),bd_initialize(),convergence_check()"".");
  PyDict_SetItemString(d, "__doc__", s);
  hw2mod2_error = PyErr_NewException ("hw2mod2.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));








/*eof initf2pywraphooks*/
  PyDict_SetItemString(d, "hw2", PyFortranObject_New(f2py_hw2_def,f2py_init_hw2));
  PyDict_SetItemString(d, "cost", PyFortranObject_New(f2py_cost_def,f2py_init_cost));
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"hw2mod2");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
