!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2pywrap_cost_costj (x, j, f2py_x_d0)
      use cost, only : costj
      real(kind=8) j
      integer f2py_x_d0
      real(kind=8) x(f2py_x_d0)
      call costj(x, j)
      end subroutine f2pywrap_cost_costj
      subroutine f2pywrap_cost_costj_grad2d (x, j_grad, f2py_x_d0)
      use cost, only : costj_grad2d
      integer f2py_x_d0
      real(kind=8) x(f2py_x_d0)
      real(kind=8) j_grad(size(x))
      call costj_grad2d(x, j_grad)
      end subroutine f2pywrap_cost_costj_grad2d
      subroutine f2pywrap_cost_costj_hess2d (x, j_hess, f2py_x_d0)
      use cost, only : costj_hess2d
      integer f2py_x_d0
      real(kind=8) x(f2py_x_d0)
      real(kind=8) j_hess(size(x),size(x))
      call costj_hess2d(x, j_hess)
      end subroutine f2pywrap_cost_costj_hess2d
      subroutine f2pywrap_cost_add_noise (x, j, f2py_x_d0)
      use cost, only : add_noise
      real(kind=8) j
      integer f2py_x_d0
      real(kind=8) x(f2py_x_d0)
      call add_noise(x, j)
      end subroutine f2pywrap_cost_add_noise
      
      subroutine f2pyinitcost(f2pysetupfunc)
      use cost, only : c_noise
      use cost, only : c_noise_amp
      interface 
      subroutine f2pywrap_cost_costj (x, j, f2py_x_d0)
      real(kind=8) j
      integer f2py_x_d0
      real(kind=8) x(f2py_x_d0)
      end subroutine f2pywrap_cost_costj 
      subroutine f2pywrap_cost_costj_grad2d (x, j_grad, f2py_x_d0)
      integer f2py_x_d0
      real(kind=8) x(f2py_x_d0)
      real(kind=8) j_grad(size(x))
      end subroutine f2pywrap_cost_costj_grad2d 
      subroutine f2pywrap_cost_costj_hess2d (x, j_hess, f2py_x_d0)
      integer f2py_x_d0
      real(kind=8) x(f2py_x_d0)
      real(kind=8) j_hess(size(x),size(x))
      end subroutine f2pywrap_cost_costj_hess2d 
      subroutine f2pywrap_cost_add_noise (x, j, f2py_x_d0)
      real(kind=8) j
      integer f2py_x_d0
      real(kind=8) x(f2py_x_d0)
      end subroutine f2pywrap_cost_add_noise
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(c_noise,c_noise_amp,f2pywrap_cost_costj,f2pywra&
     &p_cost_costj_grad2d,f2pywrap_cost_costj_hess2d,f2pywrap_cost_add_n&
     &oise)
      end subroutine f2pyinitcost

      subroutine f2py_hw2_getdims_xpath(r,s,f2pysetdata,flag)
      use hw2, only: d => xpath

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1),s(2)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_hw2_getdims_xpath
      subroutine f2py_hw2_getdims_jpath(r,s,f2pysetdata,flag)
      use hw2, only: d => jpath

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_hw2_getdims_jpath
      subroutine f2pywrap_hw2_newton (xguess, xf, jf, i2, f2py_xguess_d0&
     &, f2py_xguess_d1)
      use hw2, only : newton
      real(kind=8) jf
      integer i2
      integer f2py_xguess_d0
      integer f2py_xguess_d1
      real(kind=8) xguess(f2py_xguess_d0,f2py_xguess_d1)
      real(kind=8) xf(size(xguess),1)
      call newton(xguess, xf, jf, i2)
      end subroutine f2pywrap_hw2_newton
      
      subroutine f2pyinithw2(f2pysetupfunc)
      use hw2, only : xpath
      use hw2, only : jpath
      use hw2, only : tol
      use hw2, only : itermax
      use hw2, only : bracket_descent
      use hw2, only : bd_initialize
      use hw2, only : convergence_check
      interface 
      subroutine f2pywrap_hw2_newton (xguess, xf, jf, i2, f2py_xguess_d0&
     &, f2py_xguess_d1)
      real(kind=8) jf
      integer i2
      integer f2py_xguess_d0
      integer f2py_xguess_d1
      real(kind=8) xguess(f2py_xguess_d0,f2py_xguess_d1)
      real(kind=8) xf(size(xguess),1)
      end subroutine f2pywrap_hw2_newton
      end interface
      external f2pysetupfunc
      external f2py_hw2_getdims_xpath
      external f2py_hw2_getdims_jpath
      call f2pysetupfunc(f2py_hw2_getdims_xpath,f2py_hw2_getdims_jpath,t&
     &ol,itermax,f2pywrap_hw2_newton,bracket_descent,bd_initialize,conve&
     &rgence_check)
      end subroutine f2pyinithw2


